## The test container is created with https://github.com/dracutdevs/fedora-container

name: Fedora-32

on:
  push:
    branches:
      - 'master'
    tags:
      - '*'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: quay.io/haraldh/dracut-fedora:32
      options: "--privileged"
    timeout-minutes: 45
    strategy:
      matrix:
        test: [
          "01",
          "02",
          "03",
          "04",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "17",
          "20",
          "21",
          "22",
          "30",
          "31",
          "32",
          "35",
          "36",
          "37",
          "40",
          "41",
          "42",
          "50",
          "51",
          "52",
          "60",
          "61",
          "62",
          "99",
        ]
      fail-fast: false
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "TEST-${{ matrix.test }}"
        run: ./fedora-test-github.sh "TEST-${{ matrix.test }}" ${{ matrix.test }}
